import { createHash } from 'node:crypto';
import { decryptSecret } from '@vacti/auth';
import { pentestEngineConfig } from '@vacti/db';
import { getDb, env } from './db';
import { presignR2Get, presignR2Put, presignR2Head, type R2Config } from './r2-presign';

/**
 * Shared report-artifact cache in R2: a generated PDF / XLSX is expensive (Chromium render / image
 * embedding), so it is stored in the operator's bucket keyed by a content version and served by REDIRECTING
 * the browser straight to R2 (instant download, not streamed through the app).
 */

/** Resolve the operator's R2 config from the pentest engine-config, or null if R2 is not set up. */
export async function resolveR2Config(): Promise<R2Config | null> {
  const [cfg] = await getDb().select().from(pentestEngineConfig).limit(1);
  if (!cfg?.r2AccountId || !cfg.r2Bucket || !cfg.r2AccessKeyId || !cfg.r2SecretCiphertext) return null;
  try {
    return {
      accountId: cfg.r2AccountId,
      bucket: cfg.r2Bucket,
      accessKeyId: cfg.r2AccessKeyId,
      secretAccessKey: decryptSecret(cfg.r2SecretCiphertext, env().ENCRYPTION_KEY),
    };
  } catch {
    return null;
  }
}

/** A short content-version hash (any change in the inputs busts the cache). */
export function versionHash(parts: unknown): string {
  return createHash('sha256').update(JSON.stringify(parts)).digest('hex').slice(0, 16);
}

/** If the cached object exists, a 302 redirect Response straight to R2 (instant download); else null. */
export async function cachedRedirect(r2: R2Config, key: string): Promise<Response | null> {
  if (!(await cacheExists(r2, key))) return null;
  return new Response(null, {
    status: 302,
    headers: { Location: presignR2Get(r2, key, 600), 'X-Report-Cache': 'HIT' },
  });
}

/** Whether the cached object exists (HEAD must be signed for HEAD - a GET-signed URL 403s on HEAD). */
export async function cacheExists(r2: R2Config, key: string): Promise<boolean> {
  return fetch(presignR2Head(r2, key, 120), { method: 'HEAD' })
    .then((r) => r.ok)
    .catch(() => false);
}

/** Store generated bytes in R2 (best-effort). */
export async function cacheStore(r2: R2Config, key: string, bytes: Uint8Array, contentType: string): Promise<void> {
  await fetch(presignR2Put(r2, key, 120), {
    method: 'PUT',
    body: bytes as unknown as BodyInit,
    headers: { 'Content-Type': contentType },
  }).catch(() => {});
}
